#include "CodeGenerator.h"

#include <cstring>
#include <filesystem>
#include <fstream>

#include <EASTL/hash_map.h>
#include <EASTL/hash_set.h>
#include <EASTL/sort.h>
#include <EASTL/string.h>
#include <EASTL/vector.h>

#include "CodeWriter.h"
#include "CSharpBindingEmitter.h"
#include "ReflectionNames.h"
#include "Reflector/ProjectSolution.h"
#include "Reflector/ReflectionCore/ReflectedHeader.h"
#include "Reflector/ReflectionCore/ReflectedProject.h"
#include "Reflector/Types/Properties/ReflectedProperty.h"
#include "Reflector/Types/ReflectedType.h"
#include "StringHash.h"

namespace Lumina::Reflection
{
    namespace
    {
        constexpr size_t kStreamInitialCapacity = 10 * 1024;

        // Express the header relative to a project -I dir (longest match) or the project root.
        // A relative form lets the generated artifact survive being moved or rebuilt elsewhere.
        eastl::string ComputeSourceHeaderInclude(const FReflectedHeader& Header)
        {
            const eastl::string& Path = Header.HeaderPath;
            const FReflectedProject& Proj = *Header.Project;

            auto TryStrip = [&](const eastl::string& Prefix) -> eastl::string
            {
                if (Prefix.empty() || Prefix.size() >= Path.size())
                {
                    return {};
                }
                if (Path.compare(0, Prefix.size(), Prefix) != 0)
                {
                    return {};
                }
                size_t Pos = Prefix.size();
                while (Pos < Path.size() && (Path[Pos] == '/' || Path[Pos] == '\\'))
                {
                    ++Pos;
                }
                if (Pos >= Path.size())
                {
                    return {};
                }
                return Path.substr(Pos);
            };

            const eastl::string* BestPrefix = nullptr;
            eastl::string BestRel;
            for (const eastl::string& Dir : Proj.IncludeDirs)
            {
                eastl::string Rel = TryStrip(Dir);
                if (!Rel.empty() && (BestPrefix == nullptr || Dir.size() > BestPrefix->size()))
                {
                    BestPrefix = &Dir;
                    BestRel = eastl::move(Rel);
                }
            }
            if (BestPrefix != nullptr)
            {
                return BestRel;
            }

            if (eastl::string Rel = TryStrip(Proj.Path); !Rel.empty())
            {
                return Rel;
            }

            // No prefix matched -- keep absolute. Better to bake in the path
            // than silently emit something the compiler can't resolve.
            return Path;
        }

        void EmitFileBanner(FCodeWriter& Writer)
        {
            Writer.Line("//*************************************************************************");
            Writer.Line("// Generated by Lumina Reflection Tool. ");
            Writer.Line("// This is an auto-generated file - DO NOT EDIT.");
            Writer.Line("//*************************************************************************");
            Writer.Line();
        }

        // Paths produced by generation, relative to the workspace root.
        // Where a project's generated C++ lives. The build system pins this per target, because
        // two targets that share a module would otherwise write the same files and each would
        // see the other's output as its own having changed.
        eastl::string ProjectGeneratedDir(const eastl::string& WorkspacePath, const FReflectedProject& Project)
        {
            if (!Project.GeneratedDir.empty())
            {
                return Project.GeneratedDir;
            }

            return WorkspacePath + "/Intermediates/Reflection/" + Project.Name;
        }

        eastl::string MakeGeneratedHeaderPath(const eastl::string& WorkspacePath, const FReflectedHeader& Header)
        {
            return ProjectGeneratedDir(WorkspacePath, *Header.Project) + "/" + Header.FileName + ".generated.h";
        }

        eastl::string MakeGeneratedSourcePath(const eastl::string& WorkspacePath, const FReflectedHeader& Header)
        {
            return ProjectGeneratedDir(WorkspacePath, *Header.Project) + "/" + Header.FileName + ".generated.cpp";
        }

        // bRoutable sends a binding to the owner's Scripts/Generated, to compile into that unit's own assembly.
        eastl::string MakeGeneratedCSharpPath(const eastl::string& WorkspacePath, const FReflectedHeader& Header, bool bRoutable)
        {
            if (bRoutable && !Header.Project->CSharpBindingsDir.empty())
            {
                return Header.Project->CSharpBindingsDir + "/" + Header.FileName + ".generated.cs";
            }
            return WorkspacePath + "/Intermediates/CSharpBindings/" + Header.Project->Name + "/" + Header.FileName + ".generated.cs";
        }

        // One unity TU per project was a 52s serial spike on Runtime's critical path (more than the
        // ~43s ideal parallel time of every other Runtime TU combined), and every edit to any reflected
        // header paid all 52s. Sharding spreads the generated bodies over TUs that compile concurrently.
        //
        // kUnityShardCount is the number of shard FILES, and MUST match
        // LuminaConfig.ReflectionUnityShardCount in BuildScripts/Dependencies.lua: premake bakes the
        // shard paths into the vcxproj at generation time (deliberately a fixed list, not a glob, so
        // Visual Studio never has to re-detect generated sources), so a mismatch drops shards silently.
        //
        // How many of those files actually carry content is chosen per project below. Sharding is not
        // free: each shard re-parses the PCH and its includes' headers, so a project with a handful of
        // reflected types is better off in one TU. Unused shards are written as stubs (~0.05s each).
        constexpr int kUnityShardCount = 8;

        // Generated sources per shard. Runtime (~132) lands on the 8-shard cap; a plugin with 10 stays
        // at 1 and compiles exactly as it did before sharding.
        constexpr size_t kGeneratedSourcesPerShard = 20;

        int ShardCountFor(size_t SourceCount)
        {
            if (SourceCount <= kGeneratedSourcesPerShard)
            {
                return 1;
            }

            const size_t Wanted = (SourceCount + kGeneratedSourcesPerShard - 1) / kGeneratedSourcesPerShard;
            return static_cast<int>(Wanted < kUnityShardCount ? Wanted : kUnityShardCount);
        }

        eastl::string MakeUnityPath(const eastl::string& WorkspacePath, const FReflectedProject& Project, int Shard)
        {
            return ProjectGeneratedDir(WorkspacePath, Project)
                 + "/ReflectionUnity_" + eastl::to_string(Shard) + ".gen.cpp";
        }

        eastl::string MakeProjectIntermediateDir(const eastl::string& WorkspacePath, const FReflectedProject& Project)
        {
            return ProjectGeneratedDir(WorkspacePath, Project);
        }

        eastl::string MakeProjectCSharpDir(const eastl::string& WorkspacePath, const FReflectedProject& Project)
        {
            return WorkspacePath + R"(\Intermediates\CSharpBindings\)" + Project.Name;
        }

        constexpr const char* kUnityStubContents =
            "// Reflection unity stub.\n"
            "// This project has no reflected types yet; this file exists\n"
            "// only so the vcxproj's source list resolves. The Reflector\n"
            "// will overwrite it the moment a reflected type appears.\n";

        /// The project's precompiled header include, or nothing when it has none. Generated sources
        /// must open with their own module's PCH: naming another module's only compiles while that
        /// module happens to sit on the include path, and MSVC rejects a translation unit built with
        /// /Yu whose first content is anything else.
        eastl::string PchInclude(const FReflectedProject& Project)
        {
            if (Project.PrecompiledHeader.empty())
            {
                return {};
            }

            return eastl::string("#include \"") + Project.PrecompiledHeader + "\"\n";
        }

        // The reflected types for a header, or a shared empty list when the header has none (e.g. a header
        // whose only reflection is SCRIPT_EXPORT free functions). Avoids ReflectedTypes.at() throwing.
        const eastl::vector<eastl::unique_ptr<FReflectedType>>& TypesFor(const FReflectionDatabase& Db, FReflectedHeader* Header)
        {
            static const eastl::vector<eastl::unique_ptr<FReflectedType>> Empty;
            const auto It = Db.ReflectedTypes.find(Header);
            return It != Db.ReflectedTypes.end() ? It->second : Empty;
        }

        void WriteTextFile(const eastl::string& PathUtf8, const eastl::string& Contents)
        {
            std::filesystem::path OutputPath(PathUtf8.c_str());
            std::filesystem::create_directories(OutputPath.parent_path());

            // Binary, so the bytes on disk are exactly Contents. In text mode every \n becomes \r\n
            // and the file can never compare equal to what generated it, which defeats the skip in
            // WriteTextFileIfChanged.
            std::ofstream Stream(OutputPath, std::ios::binary);
            if (Stream.is_open())
            {
                Stream.write(Contents.c_str(), static_cast<std::streamsize>(Contents.size()));
            }
        }

        // Skips the write when the contents already match. A generated header that keeps its
        // timestamp costs nothing; rewriting one recompiles every translation unit that includes it,
        // so a change in any module would otherwise drag the whole build along.
        void WriteTextFileIfChanged(const eastl::string& PathUtf8, const eastl::string& Contents)
        {
            std::filesystem::path OutputPath(PathUtf8.c_str());

            std::error_code Ec;
            const auto Existing = std::filesystem::file_size(OutputPath, Ec);
            if (!Ec && Existing == Contents.size())
            {
                std::ifstream In(OutputPath, std::ios::binary);
                if (In.is_open())
                {
                    std::string Current((std::istreambuf_iterator<char>(In)), std::istreambuf_iterator<char>());
                    if (Current.size() == Contents.size()
                        && std::memcmp(Current.data(), Contents.c_str(), Contents.size()) == 0)
                    {
                        return;
                    }
                }
            }

            WriteTextFile(PathUtf8, Contents);
        }
    }

    FCodeGenerator::FCodeGenerator(FReflectedWorkspace* InWorkspace, const FReflectionDatabase& Database)
        : Workspace(InWorkspace)
        , ReflectionDatabase(&Database)
    {
    }

    void FCodeGenerator::GenerateCode()
    {
        // Per-project accumulator: every reflected header's .generated.cpp name. Sorted and
        // distributed over the unity shards at write time, so shard contents stay deterministic
        // (ReflectedTypes is a hash_map; its iteration order is not stable across runs, and an
        // unstable order would rewrite the unity files and dirty the build for no reason).
        eastl::hash_map<FReflectedProject*, eastl::vector<eastl::string>>   UnityPerProject;
        eastl::hash_set<FReflectedProject*>                                 DirtyProjects;
        eastl::hash_map<FReflectedProject*, eastl::hash_set<eastl::string>> ExpectedArtifacts;
        // Routed .generated.cs keyed by DIR, not project: plugin modules share one, and a per-project whitelist would have each sweep away the others'.
        eastl::hash_map<eastl::string, eastl::hash_set<eastl::string>> RoutedArtifacts;

        for (const auto& [Header, _] : ReflectionDatabase->ReflectedTypes)
        {
            // Reference-only modules are in the database so this workspace's types can name theirs.
            // Generating for them would write into another workspace's intermediates.
            if (Header->Project->bReferenceOnly)
            {
                continue;
            }

            UnityPerProject[Header->Project].push_back(Header->FileName + ".generated.cpp");

            auto& Expected = ExpectedArtifacts[Header->Project];
            Expected.insert(Header->FileName + ".generated.cpp");
            Expected.insert(Header->FileName + ".generated.h");

            const bool bRouteTypes =
                Header->Project->bRouteTypeBindings && !Header->Project->CSharpBindingsDir.empty();

            if (bRouteTypes)
            {
                RoutedArtifacts[Header->Project->CSharpBindingsDir].insert(Header->FileName + ".generated.cs");
            }
            else
            {
                Expected.insert(Header->FileName + ".generated.cs");
            }

            if (Header->bDirty)
            {
                DirtyProjects.insert(Header->Project);
                GenerateHeaderFile(Header);
                GenerateSourceFile(Header);
                GenerateCSharpFile(Header, bRouteTypes);
            }
            else if (!std::filesystem::exists(
                MakeGeneratedCSharpPath(Workspace->GetPath(), *Header, bRouteTypes).c_str()))
            {
                // Routing changed under an unchanged header, either way: the old copy is swept, so re-emit.
                GenerateCSharpFile(Header, bRouteTypes);
            }
        }

        // Headers whose ONLY reflection is SCRIPT_EXPORT free functions (no reflected type) aren't in
        // ReflectedTypes, so the loop above skips them. Process them here: they need a .generated.cpp (the
        // thunks) and a .generated.cs (the bindings), but NO .generated.h (no types, and they don't include
        // it, SCRIPT_EXPORT doesn't set bHasReflectionMacros).
        for (const auto& [Header, Fns] : ReflectionDatabase->FreeFunctions)
        {
            if (Fns.empty() || ReflectionDatabase->ReflectedTypes.find(Header) != ReflectionDatabase->ReflectedTypes.end())
            {
                continue; // empty, or already handled by the types loop (it emits free functions too)
            }

            if (Header->Project->bReferenceOnly)
            {
                continue;
            }

            UnityPerProject[Header->Project].push_back(Header->FileName + ".generated.cpp");

            auto& Expected = ExpectedArtifacts[Header->Project];
            Expected.insert(Header->FileName + ".generated.cpp");
            // The .cs is routed to the plugin/game dir (not the default), tracked separately for its sweep.
            RoutedArtifacts[Header->Project->CSharpBindingsDir].insert(Header->FileName + ".generated.cs");

            if (Header->bDirty)
            {
                DirtyProjects.insert(Header->Project);
                GenerateSourceFile(Header);
                GenerateCSharpFile(Header, /*bRoutable*/ true); // free-function-only -> routes to plugin/game
            }
        }

        // Orphan sweep: a deleted header leaves stale generated files the dirty-loop above never visits.
        // Reflection\<Project> holds .generated.{h,cpp}; CSharpBindings\<Project> holds .generated.cs.
        // Remove any whose backing header is gone (not in ExpectedArtifacts) and mark the project dirty.
        auto SweepOrphanDir = [&](FReflectedProject* Project, const eastl::string& DirPath,
            const eastl::hash_set<eastl::string>* Expected, const char* SuffixA, const char* SuffixB)
        {
            std::error_code Ec;
            const std::filesystem::path Dir(DirPath.c_str());
            if (!std::filesystem::exists(Dir, Ec))
            {
                return;
            }

            for (const auto& Entry : std::filesystem::directory_iterator(Dir, Ec))
            {
                if (Ec || !Entry.is_regular_file(Ec))
                {
                    continue;
                }

                const std::string FilenameStd = Entry.path().filename().string();
                const eastl::string Filename(FilenameStd.c_str());

                const bool bIsGenerated =
                    Filename.find(SuffixA) != eastl::string::npos ||
                    (SuffixB != nullptr && Filename.find(SuffixB) != eastl::string::npos);
                if (!bIsGenerated)
                {
                    continue;
                }

                if (Expected != nullptr && Expected->find(Filename) != Expected->end())
                {
                    continue;
                }

                std::filesystem::remove(Entry.path(), Ec);
                DirtyProjects.insert(Project);
            }
        };

        eastl::hash_set<eastl::string> SweptRoutedDirs;

        for (auto& Project : Workspace->ReflectedProjects)
        {
            if (Project->bReferenceOnly)
            {
                continue;
            }

            const auto* Expected = [&]() -> const eastl::hash_set<eastl::string>*
            {
                auto It = ExpectedArtifacts.find(Project.get());
                return It != ExpectedArtifacts.end() ? &It->second : nullptr;
            }();

            SweepOrphanDir(Project.get(), MakeProjectIntermediateDir(Workspace->GetPath(), *Project),
                Expected, ".generated.cpp", ".generated.h");
            SweepOrphanDir(Project.get(), MakeProjectCSharpDir(Workspace->GetPath(), *Project),
                Expected, ".generated.cs", nullptr);

            // Sweep the routed dir ONCE, against every project that routes there, since siblings share one.
            if (!Project->CSharpBindingsDir.empty() && SweptRoutedDirs.insert(Project->CSharpBindingsDir).second)
            {
                const auto RIt = RoutedArtifacts.find(Project->CSharpBindingsDir);
                const auto* Routed = RIt != RoutedArtifacts.end() ? &RIt->second : nullptr;
                SweepOrphanDir(Project.get(), Project->CSharpBindingsDir, Routed, ".generated.cs", nullptr);
            }
        }

        for (auto* DirtyProject : DirtyProjects)
        {
            // A project that lost its last reflected type has no UnityPerProject entry;
            // WriteUnityBuildFiles then stubs out every shard so the vcxproj still compiles cleanly.
            auto It = UnityPerProject.find(DirtyProject);
            static const eastl::vector<eastl::string> Empty;
            WriteUnityBuildFiles(DirtyProject, It != UnityPerProject.end() ? It->second : Empty);
        }

        // Stub guard: every shard must exist even for projects with zero reflected types, or premake's
        // static shard list points at missing files. Only write when one is missing (keeps incremental
        // builds fast); the __has_include stub works PCH or not.
        for (auto& Project : Workspace->ReflectedProjects)
        {
            if (Project->bReferenceOnly)
            {
                continue;
            }

            bool bAnyMissing = false;
            for (int Shard = 0; Shard < kUnityShardCount && !bAnyMissing; ++Shard)
            {
                const eastl::string Path = MakeUnityPath(Workspace->GetPath(), *Project, Shard);
                bAnyMissing = !std::filesystem::exists(std::filesystem::path(Path.c_str()));
            }

            if (!bAnyMissing)
            {
                continue;
            }

            auto It = UnityPerProject.find(Project.get());
            static const eastl::vector<eastl::string> Empty;
            WriteUnityBuildFiles(Project.get(), It != UnityPerProject.end() ? It->second : Empty);
        }
    }

    void FCodeGenerator::GenerateHeaderFile(FReflectedHeader* Header)
    {
        FCodeWriter Writer(kStreamInitialCapacity);
        WriteHeaderContent(Writer, Header);
        WriteTextFileIfChanged(MakeGeneratedHeaderPath(Workspace->GetPath(), *Header), Writer.String());
    }

    void FCodeGenerator::GenerateSourceFile(FReflectedHeader* Header)
    {
        FCodeWriter Writer(kStreamInitialCapacity);
        WriteSourceContent(Writer, Header);
        WriteTextFileIfChanged(MakeGeneratedSourcePath(Workspace->GetPath(), *Header), Writer.String());
    }

    void FCodeGenerator::GenerateCSharpFile(FReflectedHeader* Header, bool bRoutable)
    {
        FCodeWriter Writer(kStreamInitialCapacity);
        const eastl::string Path = MakeGeneratedCSharpPath(Workspace->GetPath(), *Header, bRoutable);

        if (WriteCSharpContent(Writer, Header))
        {
            WriteTextFileIfChanged(Path, Writer.String());
        }
        else
        {
            // Header contributes no C#-exposed types: drop any stale .cs so it can't linger in the build.
            std::error_code Ec;
            std::filesystem::remove(std::filesystem::path(Path.c_str()), Ec);
        }
    }

    bool FCodeGenerator::WriteCSharpContent(FCodeWriter& Writer, FReflectedHeader* Header)
    {
        const auto& Types = TypesFor(*ReflectionDatabase, Header);

        Writer.Line("//*************************************************************************");
        Writer.Line("// Generated by Lumina Reflection Tool - DO NOT EDIT.");
        Writer.Line("//*************************************************************************");
        Writer.Line("#nullable disable");
        Writer.Line();

        bool bEmittedAny = false;
        for (const auto& Type : Types)
        {
            // FReflectedClass derives FReflectedStruct, so test it first.
            if (auto* Enum = dynamic_cast<FReflectedEnum*>(Type.get()))
            {
                bEmittedAny |= CSharpBindingEmitter::EmitForEnum(Writer, *Enum);
            }
            else if (auto* Class = dynamic_cast<FReflectedClass*>(Type.get()))
            {
                bEmittedAny |= CSharpBindingEmitter::EmitForClass(Writer, *Class, *ReflectionDatabase);
            }
            else if (auto* Struct = dynamic_cast<FReflectedStruct*>(Type.get()))
            {
                bEmittedAny |= CSharpBindingEmitter::EmitForStruct(Writer, *Struct, *ReflectionDatabase);
            }
        }

        // SCRIPT_EXPORT free functions declared in this header (into their named C# static classes).
        bEmittedAny |= CSharpBindingEmitter::EmitFreeFunctions(Writer, Header, *ReflectionDatabase);

        return bEmittedAny;
    }

    void FCodeGenerator::WriteHeaderContent(FCodeWriter& Writer, FReflectedHeader* Header)
    {
        const auto& Types = TypesFor(*ReflectionDatabase, Header);
        const eastl::string FileID = Names::MakeFileIDForHeaderPath(Header->HeaderPath);

        Writer.Line("#pragma once");
        Writer.Line();
        EmitFileBanner(Writer);

        Writer.Line("#include \"Core/Reflection/ReflectedTypeAccessors.h\"");
        Writer.BlankLines(2);

        // Guard against double-inclusion without a #pragma once in the upstream header.
        Writer.Linef("#ifdef %s_generated_h", FileID.c_str());
        Writer.Line("#error Already included, missing #pragma once");
        Writer.Line("#endif");
        Writer.Linef("#define %s_generated_h", FileID.c_str());
        Writer.BlankLines(3);

        // Forward declarations + Construct_* decls + DECLARE_CLASS macros.
        for (const auto& Type : Types)
        {
            Type->DefineInitialHeader(Writer, FileID);
        }

        Writer.BlankLines(3);
        Writer.Line("//--------------------------------------------------------------------------------------");
        Writer.BlankLines(3);

        // GENERATED_BODY expansion macros.
        for (const auto& Type : Types)
        {
            Type->DefineSecondaryHeader(Writer, FileID);
        }

        Writer.BlankLines(3);
        Writer.Line("#undef CURRENT_FILE_ID ");
        Writer.Linef("\t #define CURRENT_FILE_ID %s", FileID.c_str());
    }

    namespace
    {
        // Cross-module references for every reflected type in this TU, plus one per
        // struct/class property that points at a type in another module.
        void EmitCrossModuleReferences(FCodeWriter& Writer, const FReflectionDatabase& Db,
            FReflectedHeader* Header, const eastl::vector<eastl::unique_ptr<FReflectedType>>& Types)
        {
            const eastl::string OwningApi = Names::ProjectApiMacro(Header->Project->Name);

            Writer.Line("// Begin Cross-Module References");

            for (const auto& Type : Types)
            {
                const eastl::string Kind = Type->GetTypeName();
                const eastl::string ConstructFn = Names::ConstructFunction(Kind, Type->Namespace, Type->DisplayName);
                Names::EmitGuardedCrossModuleDecl(Writer, OwningApi, Kind, ConstructFn);

                if (auto* Struct = dynamic_cast<FReflectedStruct*>(Type.get()))
                {
                    for (auto& Property : Struct->Props)
                    {
                        if (const auto* PropType = Db.GetReflectedType<FReflectedType>(FStringHash(Property->TypeName)))
                        {
                            const eastl::string PropApi = Names::ProjectApiMacro(PropType->Header->Project->Name);
                            Property->DeclareCrossModuleReference(PropApi, Writer);
                        }
                    }
                }
            }

            Writer.Line("// End Cross-Module References");
            Writer.Line();
        }

        // The per-file Register_Static_Initializer struct + trampoline.
        void EmitStaticRegistration(FCodeWriter& Writer, const eastl::string& FileID,
            const eastl::vector<eastl::unique_ptr<FReflectedType>>& Types)
        {
            bool bHasEnum = false;
            bool bHasClass = false;
            bool bHasStruct = false;

            for (const auto& Type : Types)
            {
                switch (Type->Type)
                {
                    case FReflectedType::EType::Enum:      bHasEnum   = true; break;
                    case FReflectedType::EType::Class:     bHasClass  = true; break;
                    case FReflectedType::EType::Structure: bHasStruct = true; break;
                }
            }

            Writer.Line("// ** Begin Static Registration **");
            Writer.Line();

            Writer.Linef("struct Registration_%s", FileID.c_str());
            Writer.BeginBlock();

            auto EmitInfoArray = [&](const char* FieldName, const char* ParamType, FReflectedType::EType Kind)
            {
                Writer.Linef("static constexpr Lumina::%s %s[] = {", ParamType, FieldName);
                for (const auto& Type : Types)
                {
                    if (Type->Type == Kind)
                    {
                        Type->DeclareStaticRegistration(Writer);
                    }
                }
                Writer.Line("};");
            };

            if (bHasEnum)
            {
                EmitInfoArray("EnumInfo", "FEnumRegisterCompiledInInfo", FReflectedType::EType::Enum);
            }
            if (bHasClass)
            {
                EmitInfoArray("ClassInfo", "FClassRegisterCompiledInInfo", FReflectedType::EType::Class);
            }
            if (bHasStruct)
            {
                EmitInfoArray("StructInfo", "FStructRegisterCompiledInInfo", FReflectedType::EType::Structure);
            }

            Writer.PopIndent();
            Writer.Line("};");

            // Trampoline that feeds the Registration_* struct into the compiled-in
            // registrar at translation-unit init time.
            Writer.Linef("static Lumina::FRegisterCompiledInInfo %s_Register_Static_Initializer(",
                FileID.c_str());

            auto EmitInfoPointer = [&](const char* ArrayName, bool bHasIt, bool bLast)
            {
                const char* Terminator = bLast ? "" : ",";
                if (bHasIt)
                {
                    Writer.Linef("\tRegistration_%s::%s,", FileID.c_str(), ArrayName);
                    Writer.Linef("\tstd::size(Registration_%s::%s)%s", FileID.c_str(), ArrayName, Terminator);
                }
                else
                {
                    Writer.Line("\tnullptr,");
                    Writer.Linef("\t0%s", Terminator);
                }
            };

            EmitInfoPointer("EnumInfo", bHasEnum, false);
            EmitInfoPointer("ClassInfo", bHasClass, false);
            EmitInfoPointer("StructInfo", bHasStruct, true);

            Writer.Line(");");
            Writer.Line();
            Writer.Line("// ** End Static Registration **");
            Writer.Line();
        }
    }

    void FCodeGenerator::WriteSourceContent(FCodeWriter& Writer, FReflectedHeader* Header)
    {
        Writer.Clear();

        const auto& Types = TypesFor(*ReflectionDatabase, Header);
        const eastl::string FileID = Names::MakeFileIDForHeaderPath(Header->HeaderPath);

        EmitFileBanner(Writer);

        if (const eastl::string Pch = PchInclude(*Header->Project); !Pch.empty())
        {
            Writer.Line(eastl::string(Pch.begin(), Pch.end() - 1).c_str());
        }

        Writer.Linef("#include \"%s\"", ComputeSourceHeaderInclude(*Header).c_str());
        Writer.Line("#include \"World/Entity/Components/Component.h\"");
        Writer.Line("#include \"World/Entity/Events/ECSEvent.h\"");
        // REFLECT(System) emits Meta::RegisterECSSystem<T>(). Engine modules got this transitively
        // through their pch; a game project's pch chain doesn't reach it, so declare it explicitly.
        Writer.Line("#include \"World/Entity/Systems/EntitySystem.h\"");
        Writer.Line("#include \"Core/Profiler/Profile.h\"");
        Writer.Line("#include \"Core/Math/Hash/Hash.h\"");
        Writer.Line("#include \"Core/Object/Class.h\"");
        Writer.Line("#include \"Containers/ContainerOps.h\"");
        // A REFLECT(Scriptable) class generates a forwarding shim (FScriptableBridge + the host resolver) into
        // this .cpp; pull the headers + placement-new only when the header actually declares one.
        for (const auto& T : Types)
        {
            if (T->Type == FReflectedType::EType::Class && T->HasMetadata("Scriptable"))
            {
                Writer.Line("#include \"Scripting/ScriptableObject.h\"");
                Writer.Line("#include \"Scripting/DotNet/DotNetHost.h\"");
                Writer.Line("#include <new>");
                break;
            }
        }
        // A function taking FAssetRef gets a thunk that constructs one by value; the source header may
        // only forward-declare it, so pull the definition in when any reflected function names it.
        [&]
        {
            for (const auto& T : Types)
            {
                for (const auto& Fn : T->Functions)
                {
                    for (const FFieldInfo& Arg : Fn->Arguments)
                    {
                        if (Arg.RawFieldType.find("FAssetRef") != eastl::string::npos)
                        {
                            Writer.Line("#include \"Assets/AssetRef.h\"");
                            return;
                        }
                    }
                }
            }
        }();
        Writer.Line("using namespace entt::literals;");
        Writer.BlankLines(2);

        EmitCrossModuleReferences(Writer, *ReflectionDatabase, Header, Types);

        Writer.Line("//*************************************************************************");
        Writer.Line("// Type Implementations. ");
        Writer.Line("//*************************************************************************");
        Writer.Line();
        for (const auto& Type : Types)
        {
            Type->DeclareImplementation(Writer);
        }

        Writer.BlankLines(2);
        // Static type-registration only when there ARE types. A free-function-only (SCRIPT_EXPORT) header
        // has none, and an empty registration block pulls in compiled-in-registrar machinery it doesn't need.
        if (!Types.empty())
        {
            EmitStaticRegistration(Writer, FileID, Types);
        }

        // The thunks below return blittable UDTs by C linkage (mirroring C# structs) -> C4190 is expected.
        Writer.Line("#if defined(_MSC_VER)");
        Writer.Line("#pragma warning(push)");
        Writer.Line("#pragma warning(disable: 4190)");
        Writer.Line("#endif");

        // Native size guards for any opted-in blittable C# struct mirrors (struct kinds only, not classes).
        for (const auto& Type : Types)
        {
            if (Type->Type == FReflectedType::EType::Structure)
            {
                CSharpBindingEmitter::EmitNativeLayoutCheck(Writer, static_cast<FReflectedStruct&>(*Type), *ReflectionDatabase);
            }
        }

        // Native property thunks (extern "C" exports) backing the generated C# wrappers' scalar properties.
        for (const auto& Type : Types)
        {
            if (Type->Type == FReflectedType::EType::Structure || Type->Type == FReflectedType::EType::Class)
            {
                CSharpBindingEmitter::EmitNativeThunks(Writer, static_cast<FReflectedStruct&>(*Type), *ReflectionDatabase);
            }
        }

        // Native extern "C" thunks for this header's SCRIPT_EXPORT free functions.
        CSharpBindingEmitter::EmitNativeFreeFunctions(Writer, Header, *ReflectionDatabase);

        Writer.Line("#if defined(_MSC_VER)");
        Writer.Line("#pragma warning(pop)");
        Writer.Line("#endif");
    }

    void FCodeGenerator::WriteUnityBuildFiles(FReflectedProject* Project, const eastl::vector<eastl::string>& SourceNames)
    {
        // Sort first: the caller collected these by walking hash containers, so the order varies
        // run to run. Sorted input keeps each shard's contents byte-stable, which is what lets the
        // "unchanged file" case avoid dirtying the build.
        eastl::vector<eastl::string> Sorted = SourceNames;
        eastl::sort(Sorted.begin(), Sorted.end());

        const int ActiveShards = ShardCountFor(Sorted.size());

        eastl::vector<eastl::string> Shards(kUnityShardCount);
        for (size_t Index = 0; Index < Sorted.size(); ++Index)
        {
            // Round-robin rather than contiguous chunks: adjacent generated files tend to come from
            // the same subsystem and pull the same heavy headers, so striping balances the shards.
            Shards[Index % ActiveShards] += "#include \"" + Sorted[Index] + "\"\n";
        }

        for (int Shard = 0; Shard < kUnityShardCount; ++Shard)
        {
            const eastl::string Path = MakeUnityPath(Workspace->GetPath(), *Project, Shard);
            if (Shards[Shard].empty())
            {
                WriteTextFileIfChanged(Path, eastl::string(kUnityStubContents));
                continue;
            }

            WriteTextFileIfChanged(Path, PchInclude(*Project) + Shards[Shard]);
        }
    }
}
