using System.Reflection;
using System.Text;
using LuminaBuildTool.Configuration;
using LuminaBuildTool.Core;
using LuminaBuildTool.Rules;

namespace LuminaBuildTool.ProjectFiles;

/// <summary>Writes a C# project containing every Build.cs, Target.cs and BuildRules.cs file.</summary>
public static class RulesProjectGenerator
{
    public const string ProjectName = "LuminaRules";

    public static string GetProjectPath(BuildDirectories Directories)
    {
        return Path.Combine(Directories.ProjectFilesDirectory, ProjectName + ".csproj");
    }

    /// <summary>Writes the project, returning true when it changed on disk.</summary>
    public static bool Generate(BuildDirectories Directories, RulesAssembly Assembly)
    {
        string ProjectPath = GetProjectPath(Directories);
        string ProjectDirectory = Path.GetDirectoryName(ProjectPath)!;

        StringBuilder Xml = new();
        Xml.AppendLine("""<Project Sdk="Microsoft.NET.Sdk">""");
        Xml.AppendLine();
        Xml.AppendLine("  <!-- Generated by LuminaBuildTool. Edits are overwritten. -->");
        Xml.AppendLine("  <!-- Exists so the IDE understands Build.cs and Target.cs files; the build compiles them itself. -->");
        Xml.AppendLine();
        Xml.AppendLine("  <PropertyGroup>");
        Xml.AppendLine("    <TargetFramework>net10.0</TargetFramework>");
        Xml.AppendLine("    <LangVersion>latest</LangVersion>");

        // Matches RulesCompiler: annotations without warnings, and no implicit usings, so a
        // missing using shows up in the editor exactly as it does in a build.
        Xml.AppendLine("    <Nullable>annotations</Nullable>");
        Xml.AppendLine("    <ImplicitUsings>disable</ImplicitUsings>");

        Xml.AppendLine("    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>");
        Xml.AppendLine("    <AssemblyName>LuminaRules</AssemblyName>");
        Xml.AppendLine("    <RootNamespace></RootNamespace>");

        // Left at defaults: the project sits under Intermediates, and redirecting here is too late anyway.
        Xml.AppendLine("  </PropertyGroup>");
        Xml.AppendLine();

        Xml.AppendLine("  <ItemGroup>");
        Xml.AppendLine($"""    <Reference Include="LuminaBuildTool">""");
        Xml.AppendLine($"      <HintPath>{Escape(GetBuildToolAssemblyPath())}</HintPath>");
        Xml.AppendLine("      <Private>false</Private>");
        Xml.AppendLine("    </Reference>");
        Xml.AppendLine("  </ItemGroup>");
        Xml.AppendLine();

        Xml.AppendLine("  <ItemGroup>");

        foreach (RulesFile File in Assembly.RulesFiles.OrderBy(F => F.Location, StringComparer.OrdinalIgnoreCase))
        {
            // Linked so the solution view groups them the way the source tree does, rather than
            // showing one flat list of same-named files.
            Xml.AppendLine($"""    <Compile Include="{Escape(File.Location)}">""");
            Xml.AppendLine($"      <Link>{Escape(MakeLinkPath(File))}</Link>");
            Xml.AppendLine("    </Compile>");
        }

        Xml.AppendLine("  </ItemGroup>");
        Xml.AppendLine();
        Xml.AppendLine("</Project>");

        return PathUtils.WriteFileIfChanged(ProjectPath, Xml.ToString());
    }

    /// <summary>Groups a rules file by kind and owner, so the IDE shows Modules/Runtime, not forty Build.cs.</summary>
    private static string MakeLinkPath(RulesFile File)
    {
        string Category = File.Kind switch
        {
            RulesFileKind.Target => "Targets",
            RulesFileKind.Module => File.PluginName is null ? "Modules" : "Plugins",
            _ => "Shared",
        };

        return File.PluginName is null
            ? Path.Combine(Category, Path.GetFileName(File.Location))
            : Path.Combine(Category, File.PluginName, Path.GetFileName(File.Location));
    }

    private static string GetBuildToolAssemblyPath()
    {
        return PathUtils.Normalize(Assembly.GetExecutingAssembly().Location);
    }

    private static string Escape(string Value)
    {
        return Value
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;");
    }
}
