-- Premake extension: post-process generated C# csproj XML to add analyzer/source-gen refs, raw SDK props/targets, and blank inherited C++ defines.
-- String post-processing (not premake's internal call-array, which differs across versions).

-- Fall back to _MAIN_SCRIPT_DIR so this loads before Setup.bat sets LUMINA_DIR.
local LuminaDir = os.getenv("LUMINA_DIR") or _MAIN_SCRIPT_DIR

include (path.join(LuminaDir, "BuildScripts/Logger"))

local p = premake

-- Project-scope fields; values are raw XML lines emitted verbatim.
p.api.register { name = "dotnetrawprops",    scope = "project", kind = "list:string" }  -- into a trailing <PropertyGroup>
p.api.register { name = "dotnetrawitems",    scope = "project", kind = "list:string" }  -- into a trailing <ItemGroup>
p.api.register { name = "dotnetrawtail",     scope = "project", kind = "list:string" }  -- raw XML before </Project>
p.api.register { name = "dotnetstripdefines", scope = "project", kind = "boolean" }     -- blank the inherited C++ defines

require("vstudio")
local dn = p.vstudio.dotnetbase

local function IsManaged(prj)
    return prj.dotnetrawprops or prj.dotnetrawitems or prj.dotnetrawtail or prj.dotnetstripdefines
end

local function EmitDirectoryBuildProps(prj)
    local objdir
    for cfg in p.project.eachconfig(prj) do
        objdir = cfg.objdir
        break
    end
    if not objdir then return end

    -- objdir is <ObjRoot>/<Name>/<Platform>/<Config>; strip platform+config to the per-project base.
    local restoredir = path.join(path.getdirectory(path.getdirectory(objdir)), "restore")
    local rel = path.translate(path.getrelative(prj.location, restoredir), "\\") .. "\\"

    local content = table.concat({
        "<Project>",
        "  <!-- GENERATED by premake (BuildScripts/CSharpProject.lua): route NuGet restore obj into Intermediates. -->",
        "  <PropertyGroup>",
        "    <BaseIntermediateOutputPath>" .. rel .. "</BaseIntermediateOutputPath>",
        "  </PropertyGroup>",
        "</Project>",
        "",
    }, "\n")

    local f = io.open(path.join(prj.location, "Directory.Build.props"), "w")
    if f then
        f:write(content)
        f:close()
    end
end

-- BaseIntermediateOutputPath above puts the NuGet restore obj under Intermediates, so wiping
-- Intermediates strands the next build with NETSDK1004 (missing project.assets.json) until
-- something restores again -- VS only restores on solution open, and a plain MSBuild never does.
-- Regenerating is already the documented step after a wipe, so restore here and close the gap.
local ManagedProjects = {}

local function RestoreManagedProjects()
    if #ManagedProjects == 0 then return end

    Logger.Info("Restoring NuGet packages for managed projects...")

    for _, ProjectFile in ipairs(ManagedProjects) do
        local Ok, _, Code = os.execute(string.format('dotnet restore "%s" --nologo --verbosity quiet', ProjectFile))
        if not Ok then
            Logger.Warning("Restore failed for " .. path.getname(ProjectFile) .. " (exit " .. tostring(Code) .. ").")
            Logger.Warning("Install the .NET SDK and re-run, or build once with `MSBuild Lumina.slnx -restore`.")
            return
        end
    end

    Logger.Success("NuGet restore complete.")
end

-- Only generate actions populate ManagedProjects, so clean/setup skip this untouched.
local CurrentAction = p.action.get(_ACTION)
if CurrentAction then
    local BaseOnEnd = CurrentAction.onEnd

    CurrentAction.onEnd = function()
        if BaseOnEnd then
            BaseOnEnd()
        end

        RestoreManagedProjects()
    end
end

p.override(dn, "generate", function(base, prj)
    if IsManaged(prj) then
        EmitDirectoryBuildProps(prj)
        ManagedProjects[#ManagedProjects + 1] = p.filename(prj, ".csproj")
    end

    local xml = p.capture(function() base(prj) end)

    -- Inherited C++ DefineConstants (e.g. DLL_EXPORT=__declspec(dllexport)) are invalid C#.
    if prj.dotnetstripdefines then
        xml = xml:gsub("(<DefineConstants>).-(</DefineConstants>)", "%1%2")
    end

    local lines = {}
    if prj.dotnetrawprops and #prj.dotnetrawprops > 0 then
        lines[#lines+1] = "  <PropertyGroup>"
        for _, l in ipairs(prj.dotnetrawprops) do lines[#lines+1] = "    " .. l end
        lines[#lines+1] = "  </PropertyGroup>"
    end
    if prj.dotnetrawitems and #prj.dotnetrawitems > 0 then
        lines[#lines+1] = "  <ItemGroup>"
        for _, l in ipairs(prj.dotnetrawitems) do lines[#lines+1] = "    " .. l end
        lines[#lines+1] = "  </ItemGroup>"
    end
    if prj.dotnetrawtail then
        for _, l in ipairs(prj.dotnetrawtail) do lines[#lines+1] = "  " .. l end
    end

    if #lines > 0 then
        local block = table.concat(lines, "\n") .. "\n"
        -- function replacement so '%'/'$' in the block aren't treated as gsub specials.
        xml = xml:gsub("</Project>", function() return block .. "</Project>" end, 1)
    end

    p.outln(xml)
end)
