using System;

namespace LuminaSharp;

/// <summary>
/// The engine-facing call surface: managed -&gt; native. Logging goes through the bootstrap exporter
/// table (a function pointer captured in the default ALC so it survives script reloads); every other
/// entry is a <c>[NativeCall] static partial</c> method whose <c>delegate* unmanaged</c> field, resolve,
/// and marshalling are generated by <c>NativeCallGenerator</c> (defaults: module "LuminaNative", entry
/// "LuminaSharp_{MethodName}"). Pure marshalling mechanics live in <see cref="Interop"/>.
/// </summary>
public static unsafe partial class Native
{
    private static FExporterTable Exports;

    internal static void SetExports(FExporterTable Table)
    {
        Exports = Table;
    }

    public static void Log(ELogLevel Level, string Message)
    {
        if (Exports.Log == null)
        {
            return;
        }

        Span<byte> Scratch = stackalloc byte[1024];
        Interop.FInteropString Encoded = new(Message, Scratch);
        try
        {
            Exports.Log((int)Level, Encoded.Pointer, Encoded.Length);
        }
        finally
        {
            Encoded.Free();
        }
    }

    // Component op-table access. The token returned by FindComponentOps is resolved once per type and
    // reused; the get/has/emplace/remove calls take it plus the world + entity.

    [NativeCall] public static partial IntPtr FindComponentOps(string TypeName);
    // Pure reads (try_get / any_of): non-blocking, no managed re-entry -> SuppressGCTransition.
    [NativeCall(SuppressGCTransition = true)] public static partial IntPtr GetComponent(ulong World, uint Entity, IntPtr Ops);
    [NativeCall(SuppressGCTransition = true)] public static partial int HasComponent(ulong World, uint Entity, IntPtr Ops);
    // Emplace/Remove fire on_construct/on_destroy, which can re-enter managed (signal trampolines) -> not safe.
    [NativeCall] public static partial IntPtr EmplaceComponent(ulong World, uint Entity, IntPtr Ops);
    [NativeCall] public static partial int RemoveComponent(ulong World, uint Entity, IntPtr Ops);

    // Registry signals. Connect binds a managed thunk (+ GCHandle context) to a component's
    // on_construct/on_destroy/on_update sink and returns an opaque subscription handle; Disconnect releases
    // it. Patch fires on_update for an entity's component (the manual signal pulse). Kind: 0/1/2.

    [NativeCall] public static partial IntPtr RegistryConnect(ulong World, IntPtr Ops, int Kind, IntPtr Thunk, IntPtr Context);
    [NativeCall] public static partial void RegistryDisconnect(ulong World, IntPtr Ops, int Kind, IntPtr Handle);
    [NativeCall] public static partial void RegistryPatch(ulong World, uint Entity, IntPtr Ops);


    // Appends a script of the named class to an entity and binds it; returns the new instance's handle.
    [NativeCall] public static partial IntPtr AddEntityScript(ulong World, uint Entity, string ClassName);

    // Lookup over the native CEntityScript component. Class-keyed, so these find a C++ script too. The
    // FindEntityScripts buffer may be null/0 to just ask for the count (the return value is the true total
    // either way, so an under-sized buffer is retried rather than silently truncating).
    [NativeCall] public static partial IntPtr FindEntityScript(ulong World, uint Entity, string ClassName);
    [NativeCall] public static partial int FindEntityScripts(ulong World, uint Entity, string ClassName, void** OutScripts, int Capacity);

    // Removes the slot holding the given instance handle, destroying the managed instance.
    [NativeCall] public static partial void RemoveEntityScript(ulong World, uint Entity, IntPtr Instance);

    // entt::runtime_view iteration for the C# View<...>. Native gathers a CHUNK of entities + parallel
    // component pointers per call (one crossing per chunk). Hand-written delegate* binds: the chunk
    // pointers (uint*, void**) aren't shapes the [NativeCall] generator covers. See DotNetView.cpp.

    public static IntPtr ViewBegin(ulong World, IntPtr* IncludeOps, int NInc, IntPtr* ExcludeOps, int NExc)
    {
        return ViewBegin_(World, IncludeOps, NInc, ExcludeOps, NExc);
    }

    public static int ViewNextChunk(IntPtr State, uint* OutEntities, IntPtr* OutPtrs, int MaxCount, int NInclude)
    {
        return ViewNextChunk_(State, OutEntities, OutPtrs, MaxCount, NInclude);
    }

    public static void ViewEnd(IntPtr State)
    {
        ViewEnd_(State);
    }

    private static readonly delegate* unmanaged[Cdecl]<ulong, IntPtr*, int, IntPtr*, int, IntPtr> ViewBegin_ =
        (delegate* unmanaged[Cdecl]<ulong, IntPtr*, int, IntPtr*, int, IntPtr>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewBegin");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, uint*, IntPtr*, int, int, int> ViewNextChunk_ =
        (delegate* unmanaged[Cdecl]<IntPtr, uint*, IntPtr*, int, int, int>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewNextChunk");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, void> ViewEnd_ =
        (delegate* unmanaged[Cdecl]<IntPtr, void>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewEnd");

    // Asset loading. String args are UTF-8 encoded by the generated marshalling; the engine VFS resolves
    // the path. Backs the C# Asset API.

    [NativeCall] public static partial IntPtr LoadObject(string Path);
    [NativeCall] public static partial bool AssetExists(string Path);
    [NativeCall] public static partial void LoadObjectAsync(string Path, IntPtr Callback);

    /// <summary>A loaded object's asset path (registry reverse lookup), or "" if it has none.</summary>
    [NativeCall] public static partial string GetObjectPath(IntPtr Object);

    // Weak-handle validity backing NativeObject. ObjectGetHandle packs a live CObject*'s (Index, Generation)
    // as Generation<<32 | Index (Index = -1 if untracked); ObjectResolve returns the live pointer only if that
    // handle still names a live, non-destroyed object, else zero. Pure reads -> SuppressGCTransition.
    [NativeCall(SuppressGCTransition = true)] public static partial long ObjectGetHandle(IntPtr Object);
    [NativeCall(SuppressGCTransition = true)] public static partial IntPtr ObjectResolve(int Index, int Generation);

    // Per-CObject managed-instance cache backing Wrapper<T>.ForObject: Get returns the weak GC handle of the
    // wrapper this object already has (or zero), Set installs one and frees whatever it replaces (a zero
    // handle just clears). See Core/Object/ManagedInstance.h for the ownership rules.
    [NativeCall(SuppressGCTransition = true)] public static partial IntPtr ObjectGetManagedInstance(IntPtr Object);
    [NativeCall(SuppressGCTransition = true)] public static partial void ObjectSetManagedInstance(IntPtr Object, IntPtr Handle);

    // Frees every cached managed instance. Called from the script teardown contract before the collectible ALC
    // unloads: Scriptable subclass instances are held by STRONG handles in that table and would pin it.
    [NativeCall] public static partial void ReleaseAllManagedInstances();

    // Generic per-property-type accessors. The Reflector emits these for non-blittable properties
    // (FString/FName/object ref) with the property's FProperty* token (Prop) resolved once and cached;
    // C is the container (the live component/object handle). Blittable properties never reach here -- they
    // read/write native memory directly at the property's offset.

    // FName get = the generated two-pass buffer ABI (an interned id has to be resolved to text natively);
    // string set / object ref = generated string/pointer args. There is deliberately no PropGetString: an
    // FString is read in place off the property's offset via NativeMarshal.ReadString, with no crossing.

    [NativeCall] public static partial void PropSetString(IntPtr C, IntPtr Prop, string Value);
    [NativeCall] public static partial string PropGetName(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetName(IntPtr C, IntPtr Prop, string Value);
    [NativeCall] public static partial IntPtr PropGetObject(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetObject(IntPtr C, IntPtr Prop, IntPtr Object);

    // Asset reference: the virtual path, which is how C# stores one too (Lumina.FSoftObjectPath). Same
    // two-pass buffer ABI as PropGetName.
    [NativeCall] public static partial string PropGetAssetPath(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetAssetPath(IntPtr C, IntPtr Prop, string Path);

    // The element ops table for an array property, so a TVector<T> view can be built over any reflected
    // array -- including one appended to a minted script class, which has no generated per-property export.
    [NativeCall] public static partial IntPtr PropVectorOps(IntPtr Prop);
    [NativeCall] public static partial IntPtr PropMapOps(IntPtr Prop);

    // Assigns an FString at a raw address; the write half of a string container element (reads decode the
    // native string in place with no crossing). See ElementMarshal (EElementKind.String).
    [NativeCall] public static partial void StringAssign(IntPtr String, string Value);

    // Assigns a TObjectPtr at a raw address, releasing the old reference and adding one to the new. The write
    // half of an object container element: a raw pointer store would skip the refcount. See ElementMarshal (EElementKind.ObjectRef).
    [NativeCall] public static partial void SetObjectPtr(IntPtr Slot, IntPtr Object);

    // FName interning. Address-based, not property-based, so the same pair serves a member and an element of
    // a TVector<FName>. FName itself is POD, so nothing else about it crosses -- reads and writes of the
    // value are plain in-place memory access, like any other blittable mirror.
    [NativeCall] public static partial void NameFromString(string Value, IntPtr OutName);
    [NativeCall] public static partial string NameToString(IntPtr Name);

    [NativeCall] public static partial ulong DelegateBind(IntPtr Delegate, IntPtr Thunk, IntPtr Context);
    [NativeCall] public static partial void DelegateUnbind(IntPtr Delegate, ulong Handle);
}
